export default {
    input: 'dist/index.js',
    external: [
        '@angular/core',
        '@angular/common',
        '@angular/forms',
        '@angular/common/http',
        '@ngrx/effects',
        '@angular/router',
        'rxjs',
        'rxjs/observable/of',
        'rxjs/operators',
        'rxjs/add/operator/do',
        'rxjs/add/operator/map',
        '@ngrx/store',
        '@ngrx/router-store',
        'rxjs/operators/map',
        'rxjs/Observable',
        'rxjs/add/observable/throw',
        'rxjs/add/operator/catch',
    ],
    output: {
        file: 'dist/bundles/drfjwtauth.umd.js',
        sourcemap: false,
        format: 'umd',
        name: 'ng.drfjwtauth',
        globals:
            {
                '@angular/core': 'ng.core',
                '@angular/common': 'ng.common',
                '@angular/common/http': 'ng.common.http',
                '@angular/router': 'ng.router',
                '@angular/forms': 'ng.forms',
                'rxjs/Observable': 'Rx',
                'rxjs/ReplaySubject': 'Rx',
                'rxjs/add/operator/map': 'Rx.Observable.prototype',
                'rxjs/observable/of': 'Rx.Observable',
                'rxjs/operators/map': 'Rx',
                'rxjs/operators': 'Rx',
                'rxjs': 'Rx',
                '@ngrx/store': 'ngrx.store',
                '@ngrx/effects': 'ngrx.effects',
                '@ngrx/router-store': 'ngrx.routerStore',
            },

    }
}